Use set_cookie() to merge CookieJar objects
Problem:
- browser_cookie3 returns http.cookiejar.CookieJar
- CookieJar doesn't have .update() method
- Error: 'CookieJar' object has no attribute 'update'

Solution:
- Iterate over parent_cookies manually
- Use cookies.set_cookie(cookie) for each cookie
- This is the standard way to merge CookieJar objects

Now parent domain cookies should actually merge into the main jar.